-- MySQL Script generated by MySQL Workbench and modified to comply with SQLite3

-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `Id` INT PRIMARY KEY,
  `Name` VARCHAR(100) NOT NULL
);


-- -----------------------------------------------------
-- Table `Dependency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dependency` ;

CREATE TABLE IF NOT EXISTS `Dependency` (
  `Id` INT PRIMARY KEY,
  `Name` VARCHAR(100) NOT NULL,
  `Tooltip` VARCHAR(500) NULL,
  `CategoryId` INT NOT NULL,
  `MultipleInstances` TINYINT NOT NULL DEFAULT 0,
  `InputField1` TINYINT NOT NULL DEFAULT 0,
  `InputFieldLabel` VARCHAR(500) NULL,
  `InputField2` TINYINT NOT NULL DEFAULT 0,
  `InputField2Label` VARCHAR(500) NULL,
  `DropdownMenu` TINYINT NOT NULL DEFAULT 0,
  `DropdownOptions` VARCHAR(500) NULL,
  `RadioButtons` TINYINT NOT NULL DEFAULT 0,
  `RadioOptions` VARCHAR(500) NULL,
  `CheckboxButtons` TINYINT NOT NULL DEFAULT 0,
  `CheckboxOptions` VARCHAR(500) NULL,
  `Slider` TINYINT NOT NULL DEFAULT 0,
  `SliderMin` INT NULL,
  `SliderMax` INT NULL,
  `SliderRange` TINYINT NOT NULL DEFAULT 0,
  `DateTimePicker` TINYINT NOT NULL DEFAULT 0,
  `DateTimeRange` TINYINT NOT NULL DEFAULT 0,
  `RequiredDependencyId` INT NULL,
  `RecommendedDependencyId` INT NULL,
  CONSTRAINT `fk_Dependency_Category1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `Category` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX `fk_Dependency_Category1_idx` ON `Dependency` (`CategoryID` ASC);


-- -----------------------------------------------------
-- Table `WorkOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkOrder` ;

CREATE TABLE IF NOT EXISTS `WorkOrder` (
  `Id` INT PRIMARY KEY,
  `Name` VARCHAR(100) NOT NULL,
  `Start` DATETIME NULL,
  `End` DATETIME NULL
);


-- -----------------------------------------------------
-- Table `WorkOrderToDependency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkOrderToDependency` ;

CREATE TABLE IF NOT EXISTS `WorkOrderToDependency` (
  `DependencyInstanceId` INT NOT NULL,
  `DependencyId` INT NOT NULL,
  `WorkOrderId` INT NOT NULL,
  `InputField1Value` VARCHAR(500) NULL,
  `InputField2Value` VARCHAR(500) NULL,
  `DropdownOptionSelected` VARCHAR(100) NULL,
  `RadioOptionSelected` VARCHAR(100) NULL,
  `CheckboxOptionSelected` VARCHAR(100) NULL,
  `SliderMinValue` INT NULL,
  `SliderMaxValue` INT NULL,
  `Start` DATETIME NULL,
  `End` DATETIME NULL,
  PRIMARY KEY (`DependencyInstanceId`, `DependencyId`, `WorkOrderId`),
  CONSTRAINT `fk_WorkOrderToDependency_Dependency`
    FOREIGN KEY (`DependencyId`)
    REFERENCES `Dependency` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkOrderToDependency_WorkOrder1`
    FOREIGN KEY (`WorkOrderId`)
    REFERENCES `WorkOrder` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX `fk_WorkOrderToDependency_Dependency_idx` ON `WorkOrderToDependency` (`DependencyId` ASC);
CREATE INDEX `fk_WorkOrderToDependency_WorkOrder1_idx` ON `WorkOrderToDependency` (`WorkOrderId` ASC);


-- -----------------------------------------------------
-- Table `Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Currency` ;

CREATE TABLE IF NOT EXISTS `Currency` (
  `Id` INT PRIMARY KEY,
  `Country` VARCHAR(100) NOT NULL,
  `Code` CHAR(3) NOT NULL
);
