# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.14

    - name: Install SQLite3
      run: sudo apt-get install -y sqlite3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Initialize SQLite Database
      run: sqlite3 Optiplan.db -init OptiplanSqlite3.sql

    - name: Test
      run: dotnet test --no-build --verbosity normal
